# Generated by Django 3.1.5 on 2022-02-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Filmes',
        ),
    ]
