# Generated by Django 3.1.5 on 2022-02-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_auto_20220209_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filmes',
            new_name='Filme',
        ),
    ]
