# Generated by Django 3.1.5 on 2022-02-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_auto_20220209_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='userId',
            new_name='id_filme',
        ),
        migrations.AlterField(
            model_name='filme',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
