# Generated by Django 3.1.5 on 2022-02-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_auto_20220209_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='id_filme',
            field=models.IntegerField(unique=True),
        ),
    ]
