# Generated by Django 3.1.5 on 2022-02-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_auto_20220209_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='id_filme',
            field=models.IntegerField(),
        ),
    ]
