# Generated by Django 3.1.5 on 2022-02-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0006_auto_20220209_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
