# Generated by Django 3.1.5 on 2022-02-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0007_auto_20220209_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='id_filme',
        ),
    ]
