# Generated by Django 3.1.5 on 2022-03-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0008_remove_filme_id_filme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_filmes', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('urls_imgs_185', models.CharField(max_length=400)),
                ('urls_imgs_500', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('id_filme', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
    ]
