# Generated by Django 3.1.5 on 2022-03-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0011_auto_20220302_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
